services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'
      - "15672:15672"
      - '61613:61613'
    volumes:
      - "./docker/rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"